language: node_js
node_js:
  - "8"
install:
  - yarn install
  - cd docs && yarn install && cd ../
  - cd examples && yarn install && cd ../
  - make build
before_script:
  yarn run eslint
before_deploy:
  cd docs && yarn run build && cd ../
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/build
  email: ian.stewart@anchor.chat
  name: IanCStewart
  on:
    branch: master
notifications:
  email: false
